### ISSUE TITLE
swift build error

### ISSUE THREAD

**Issue by SamAlbuga** [Zewo/HTTP#6]
Hello, I'm getting this error when trying to build:
`NoSources("/home/user/app/Packages/CURIParser-0.4.0/include")`

**Comment by goloveychuk** [comment]
@SamAlbuga what toolchain you are using?
0.4.0 version is for latest, develop one. 
If you are using stable 2.2 swift, try minor=3 version

**Comment by paulofaria** [comment]
swift 3 feb 8 dev snapshot works as well.

**Comment by SamAlbuga** [comment]
@goloveychuk I'm using swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a-ubuntu15.10. I got more compilation errors when setting minor to 3

**Comment by Danappelxx** [comment]
We don't support that snapshot. 02-08 works with 0.3, 03-16/03-24 work with 0.4.
